### ISSUE TITLE
Code breaking while preprocessing context embedding file.

### ISSUE THREAD

**Issue by tim-hari** [orenmel/lexsub#1]
python jcs/text2numpy.py lexsub_contexts lexsub_contexts_out

File "/home/user/PycharmProjects/lexsub-master/jcs/text2numpy.py", line 30, in <module>
    new_matrix[i, :] = matrix[word]
ValueError: could not broadcast input array from shape (600) into shape (1)

**Comment by orenmel** [comment]
My guess is that the reason for this is that the embeddings file you're using has a header line. If so, try to delete it and run the code again.

**Comment by tim-hari** [comment]
> My guess is that the reason for this is that the embeddings file you're using has a header line. If so, try to delete it and run the code again.

i've tried removing header file and ran the same, followed by other error

Traceback (most recent call last):
  File "/home/user/Software/pycharm-community-2017.3.2/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/PycharmProjects/lexsub-master/jcs/text2numpy.py", line 30, in <module>
    new_matrix[i, :] = matrix[word]
ValueError: could not broadcast input array from shape (288) into shape (600)

**Comment by orenmel** [comment]
This seems to indicate that your embeddings file is corrupted in the sense that it contains a line with only 288 numerical values, although the dimensionality is 600.

**Comment by tim-hari** [comment]
> This seems to indicate that your embeddings file is corrupted in the sense that it contains a line with only 288 numerical values, although the dimensionality is 600.

Figured it out, somehow its corrupted.
Its working fine now :+1:
