### ISSUE TITLE
testfile option

### ISSUE THREAD

**Issue by gmichalo** [orenmel/lexsub#10]
In the evaluation example in the readme for the testfile option, the file that was chosen had the path datasets/lst_all.preprocessed.

I was wondering why this file is chosen instead of the datasets/lst_test.preprocessed?

Is the results of the paper for the datasets/lst_all.preprocessed or for the datasets/lst_test.preprocessed ?

**Comment by orenmel** [comment]
The evaluation was on the entire dataset, except where explicitly stated
that only the test set was used (Table 4). As far as I remember, this was
to follow the choices made in prior works.
